### ISSUE TITLE
I am getting ban for using this

### ISSUE THREAD

**Issue by barrywilcox** [open-osrs/hosting#620]
Everyone of my friends says they got a ban for using this. Just want you to know ok?

Can we expect this to be bypassed? 

Please put jagex in their place, they are losers!

**Comment by barrywilcox** [comment]
Any news on which actions will be taken now that jagex is hostile against us?

**Comment by Owain94** [comment]
> Any news on which actions will be taken now that jagex is hostile against us?

This is not a forum, please use our Discord server for any questions.
